# Generated by Django 2.2.9 on 2020-03-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True)),
                ('client_logo', models.URLField(blank=True, max_length=255, null=True)),
                ('client_added', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('MenuIcon', models.CharField(max_length=20)),
                ('userAccess', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spoc_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoc_name', models.CharField(max_length=255)),
                ('spoc_email', models.CharField(max_length=50)),
                ('spoc_mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=255)),
                ('number_of_bots', models.CharField(max_length=50)),
                ('number_of_groups', models.CharField(max_length=50)),
                ('number_of_intents', models.CharField(max_length=50)),
                ('number_of_subAccounts', models.CharField(max_length=50)),
                ('number_of_interaction', models.CharField(max_length=50)),
                ('billing_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubMenuName', models.CharField(max_length=20)),
                ('Link', models.CharField(max_length=255)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='client_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.client')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='client_subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_end_date', models.DateTimeField()),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='spoc_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.spoc_details'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.subscription'),
        ),
    ]
